'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MMLCHelper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _09_334_別雲間() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_09_334_別雲間", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _21_434敬酒歌___何達() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_21_434敬酒歌___何達", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Awesome_Face_Song__Low_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Awesome_Face_Song__Low_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Doge_Adventure__animated_music_video__MrWeebl__Full_HD_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Doge_Adventure__animated_music_video__MrWeebl__Full_HD_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Favicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Favicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Happy_music___Daydreaming__Low_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Happy_music___Daydreaming__Low_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Main_Reaktor___Awakening__NCS_Release____Full_HD__() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Main_Reaktor___Awakening__NCS_Release____Full_HD__", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Nyan_Cat__original___Low_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Nyan_Cat__original___Low_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Snoop_dogg_Smoke_weed_everyday_HD__dubstep_remix___Antoine_Daniel_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Snoop_dogg_Smoke_weed_everyday_HD__dubstep_remix___Antoine_Daniel_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property The_Official_Illuminati_Theme_Song__HD_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("The_Official_Illuminati_Theme_Song__HD_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Troll_Song__Low_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Troll_Song__Low_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ultimate_MLG___Most_annoying_video_ever__Low__360p_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ultimate_MLG___Most_annoying_video_ever__Low__360p_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Yee__Low__360p_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Yee__Low__360p_", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
